### PR TITLE
app icon update

### PR DESCRIPTION
**Pull request by prackode**

### CODE REVIEW

**Comment by prackode** [comment]
fixes #5 @Shamoyeeta

**Comment by prackode** [comment]
you have accepted my request for issue #5 but it is not showing in my 'Currently Accepted PRs'' section
pls look into the same

**Review by Shamoyeeta — APPROVED** [review]

**Comment by Shamoyeeta** [comment]
@prackode Try requesting the issue once again asap

**Comment by prackode** [comment]
Assignment Request for [Issue #5](https://github.com/ContriHUB/Amuse/issues/5) of [Amuse](https://github.com/ContriHUB/Amuse) cannot be made by you currently.

**Comment by prackode** [comment]
its not yet updated on the website, pls check @Shamoyeeta

**Pull request merged**
